INSERT INTO `groupproject`.`staff` (`id`, `first_name`, `last_name`) VALUES ('-1', 'Lovely', 'Luna');
INSERT INTO `groupproject`.`interviewer` (`id`) VALUES ('-1');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `notes`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-3', 'Good', '10', '1', '-1', '1');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `notes`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-2', 'Great', '5', '1', '-1', '10');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `notes`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-1', 'Perfect', '6', '2', '-1', '1');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `notes`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-4', 'Perfect', '10', '1', '-1', '22');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-6', '2', '3', '5', '5');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-7', '1', '2', '-1', '4');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-8', '3', '1', '-1', '29');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-9', '4', '1', '-1', '7');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-10', '8', '1', '-1', '8');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-11', '6', '5', '-1', '9');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-12', '7', '8', '-1', '3');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-13', '2', '7', '-1', '8');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-14', '10', '1', '-1', '31');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `notes`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-15', 'xzcZXCBV dsfwearaerg sdgf gdsfgfd', '7', '1', '5', '11');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-16', '7', '1', '5', '12');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-17', '4', '1', '6', '13');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-18', '4', '1', '6', '30');
INSERT INTO `groupproject`.`assessment_centre_response` (`id`, `points`, `candidate_id`, `fk_interviewer_id`, `question_id`) VALUES ('-19', '8', '1', '-1', '28');
