INSERT INTO `groupproject`.`staff` (`id`) VALUES (-1);
INSERT INTO `groupproject`.`interviewer` (id) VALUES (-1);
INSERT INTO question (id, question_body, question_type) VALUES(1, 'Tell me about yourself.', 0);
INSERT INTO question (id, question_body, question_type) VALUES(2, 'Why did you do [your degree]? How do you think it would fit if you were to become a [stream] consultant?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(3, 'Why do you have a passion for tech?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(4, 'What do you know about FDM and the role?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(5, 'What are your career ambitions? Where do you see yourself 5 years from now?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(6, 'What are you doing outside of FDM/Uni to improve your skills?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(7, 'How would your friends and family describe you as a person?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(8, 'What is it about the industry that excites you?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(9, 'Why should we hire you?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(10, 'Are you willing to relocate?', 0);
INSERT INTO question (id, question_body, question_type) VALUES(11, 'What do you like to do in your spare time?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(12, 'Do you prefer the big picture or small details?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(13, 'Can you describe a project you have previously worked on and what was the outcome? ', 1);
INSERT INTO question (id, question_body, question_type) VALUES(14, 'What do you value about yourself?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(15, 'If you had the opportunity, what would you like to teach others?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(16, 'How do you approach uncertainty?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(17, 'What does an ideal day look like to you?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(18, 'Explain to me a time, where you might have met some adversity. What did you do to overcome it? And what was the result?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(19, 'What is the most challenging/exciting project you have worked on in the past 2 years?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(20, 'Describe a time when you have experienced a significant project change last minute. How did you handle it and complete the project on time?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(21, 'What is the role of a continuous integration system in an automated build process?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(22, 'What coding language are you most familiar/comfortable with?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(23, 'Tell me about a time where you developed a system or piece of code using a particular language.', 1);
INSERT INTO question (id, question_body, question_type) VALUES(24, 'How do you keep up with the latest trends, advances and programming languages in this field?', 1);
INSERT INTO question (id, question_body, question_type) VALUES(25, 'How do you judge success?', 2);
INSERT INTO question (id, question_body, question_type) VALUES(26, 'What has been your most significant achievement?', 2);
INSERT INTO question (id, question_body, question_type) VALUES(27, 'Can you describe a time where you were facing a setback and what did you do to get through it?', 2);
INSERT INTO question (id, question_body, question_type) VALUES(28, 'Can you describe a situation where you had to work collaboratively to achieve a goal?', 2);
INSERT INTO question (id, question_body, question_type) VALUES(29, 'How would you approach an uncertain/ambiguous situation?', 2);
INSERT INTO question (id, question_body, question_type) VALUES(30, 'Tell me about a time you had to work with someone whose personality/work style clashed with yours.', 2);
INSERT INTO question (id, question_body, question_type) VALUES(31, 'Tell me about a time you had to manage multiple responsibilities.', 2);
INSERT INTO question (id, question_body, question_type) VALUES(32, 'Tell me about a time where you disagreed with your coworkers. How did you resolve it?', 2);
INSERT INTO question (id, question_body, question_type) VALUES(33, 'If you’re on a deserted island, with no reception, what one item would you take along?', 3);
INSERT INTO question (id, question_body, question_type) VALUES(34, 'What makes you the best candidate for this position?', 3);
INSERT INTO question (id, question_body, question_type) VALUES(35, 'What would you do if your company can’t send you a work laptop?', 3);
INSERT INTO question (id, question_body, question_type) VALUES(36, 'Every CV has one lie in it. What is yours?', 3);
